// hexagons/index.tsx
'use client'

import type { CSSProperties, JSX } from 'react'
import { useEffect, useRef, useState } from 'react'

import type { HexagonPatternsType } from 'nucleify'
import {
  getHexagonPoints,
  PATTERN_UPDATE_INTERVAL,
  updateImagesPerRow,
} from 'nucleify'

import './_index.scss'

export function NucAnimationHexagons(): JSX.Element {
  const containerRef = useRef<HTMLDivElement | null>(null)
  const [hexagonRows, setHexagonRows] = useState<HexagonPatternsType>([])

  useEffect(() => {
    updateImagesPerRow(
      containerRef.current,
      () => undefined,
      () => undefined,
      setHexagonRows
    )

    const interval = setInterval(() => {
      requestAnimationFrame(() => {
        updateImagesPerRow(
          containerRef.current,
          () => undefined,
          () => undefined,
          setHexagonRows
        )
      })
    }, PATTERN_UPDATE_INTERVAL)

    return () => {
      clearInterval(interval)
    }
  }, [])

  return (
    <div
      ref={containerRef}
      className="hexagon-rows-container"
      style={{ width: '100%', minHeight: '70vh', overflow: 'hidden' }}
    >
      {hexagonRows.map((row, rowIndex) => (
        <div
          key={rowIndex}
          className="hexagon-row-container"
          style={{ display: 'flex' }}
        >
          {['hexagon-container n1', 'hexagon-container n2'].map(
            (containerClass, containerIndex) => (
              <div
                key={containerIndex}
                className={containerClass}
                style={{ opacity: 0.15 + 0.015 * rowIndex, lineHeight: 0 }}
              >
                <svg width={row[containerIndex].length * 40} height="40">
                  {row[containerIndex].map((opacity, imgIndex) => (
                    <polygon
                      key={imgIndex}
                      className={`hexagon-${imgIndex}`}
                      style={{ opacity } as CSSProperties}
                      points={getHexagonPoints(20 + imgIndex * 40, 20, 20)}
                      stroke="#10b981"
                      strokeWidth={2}
                    />
                  ))}
                </svg>
              </div>
            )
          )}
        </div>
      ))}
    </div>
  )
}

// hexagons/index.vue
<template>
  <div ref="containerRef" class="hexagon-rows-container">
    <client-only>
      <deferred-content>
        <div
          v-for="(row, rowIndex) in hexagonRows"
          :key="rowIndex"
          class="hexagon-row-container"
        >
          <div
            v-for="(containerClass, containerIndex) in [
              'hexagon-container n1',
              'hexagon-container n2',
            ]"
            :key="containerIndex"
            :class="containerClass"
            :style="{ opacity: 0.15 + 0.015 * rowIndex }"
          >
            <svg
              :width="row[containerIndex].length * 40"
              height="40"
              style="display: block"
            >
              <polygon
                v-for="(opacity, imgIndex) in row[containerIndex]"
                :key="imgIndex"
                :class="'hexagon-' + imgIndex"
                :style="{ opacity: opacity }"
                :points="getHexagonPoints(20 + imgIndex * 40, 20, 20)"
                stroke="#34d999"
                stroke-width="2"
              />
            </svg>
          </div>
        </div>
      </deferred-content>
    </client-only>
  </div>
</template>

<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from 'vue'

import {
  getHexagonPoints,
  PATTERN_UPDATE_INTERVAL,
  updateImagesPerRow,
} from 'nucleify'

const containerRef = ref<HTMLElement | null>(null)
const imagesPerRow = ref(0)
const totalRows = ref(0)
const hexagonRows = ref<number[][][]>([])

onMounted(() => {
  updateImagesPerRow(containerRef, imagesPerRow, totalRows, hexagonRows)

  const interval = setInterval(() => {
    requestAnimationFrame(() => {
      updateImagesPerRow(containerRef, imagesPerRow, totalRows, hexagonRows)
    })
  }, PATTERN_UPDATE_INTERVAL)

  onBeforeUnmount(() => {
    clearInterval(interval)
  })
})
</script>

<style lang="scss">
@import 'index';
</style>
